projectName: conference
nameSpace: dev
appType:
  frontend: webapp
  api: api

replicaSet: 1

webappContainerService:
  type: ClusterIP  # {{ .Values.webappContainerService.type }}
  port: 3000       # {{ .Values.webappContainerService.port }}


domainName: oostvoort.work                # {{ .Values.domainName }}

subDomainName: 
  conference: dev-meet                 # {{ .Values.subDomainName.conference }}

dockerImage: oostvoort/conference-rs:prod
