name: Docker build and deploy
on:
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          #registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}    

    #  - name: Build, tag, and push image
   #     id: build-image
  #      run: |
 #         docker build -t oostvoort/conference-rs:dev .
#          docker push oostvoort/conference-rs:dev
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "oostvoort/conference-rs:dev"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.TOKEN_CONFERENCE }}" | tr -d '\r' | ssh-add -
          ls -al ~/
          mkdir -p ~/.ssh
          ls -al ~/.ssh
          chmod 700 ~/.ssh
          ls -al ~/.ssh
          ssh-keyscan -T 300 -p 2201 161.49.100.214 >> ~/.ssh/known_hosts
          ls -al ~/.ssh
          cat ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "executing ssh command"
          ssh tabula-rasa@161.49.100.214 -p 2201 -C "docker compose -f ~/conference/dev/docker-compose.yml pull && docker compose -f ~/conference/dev/docker-compose.yml up --force-recreate -d"
#run
