name: Docker build and deploy to CapRover
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to CapRover
        uses: docker/login-action@v2
        with:
          #registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}    

      - name: Build, tag, and push image to CapRover
        id: build-image
        run: |
          docker build -t  . 
          docker tag built-image-name oostvoort/conference-rs:dev
          docker push oostvoort/conference-rs:dev
                   
